exclude: |
    (?x)^(
        .*__init__.py$|
        .*setup.py$|
    )$

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        args: ['--unsafe']
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=800']
    -   id: check-json
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.292
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        name: 'detect-secrets'
        args: ['--exclude-files', '.*\.ipynb$', ]
    -   id: detect-secrets
        name: 'detect-secrets-jupyter'
        args: [
            '--exclude-files', '.*[^i][^p][^y][^n][^b]$',
            '--exclude-lines', '"(hash|id|image/\w+)":.*',
        ]

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        additional_dependencies: ["toml"]
        language_version: python3.10

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        require_serial: true
        language: system
        types: [ python ]
        args: [
            --allow-redefinition,
            --ignore-missing-imports,
            --disable-error-code=union-attr,
            --disable-error-code=attr-defined,
            --disable-error-code=call-overload,
            --disable-error-code=call-arg,
            --disable-error-code=no-any-return,
            --disallow-incomplete-defs,
            --disallow-untyped-defs,
            ]

-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        additional_dependencies: ["toml"]
        args:
        - --ignore=D100,D203,D405,D104,D416,D212,D213

-   repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
