services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
    expose:
      - 6333
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/config.yaml
    volumes:
      - ./qdrant_data:/qdrant_data

configs:
  qdrant_config:
    file: conf/base/qdrant_config.yaml
