name: ai_news

channels:
  # - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - transformers>=4.34.0 
  - pip
  - pip:
    - xmltodict
    - rich
    - arxiv
    - tokenizers>=0.13.3
    # - flash_attn
    - ctransformers
    - scikit-learn
    - tiktoken
    - newsapi-python
    - newspaper3k
    - gnews

    # python utils
    - fire
    - tqdm
    - numpy
    - pandas
    - pre-commit
    - mypy
    - loguru

    # viz
    - matplotlib
    - plotly
    - umap-learn

    # deep-learning
    - accelerate
    - langchain
    - langchain-community
    - sentencepiece
    - sentence_transformers
    - huggingface_hub
    - InstructorEmbedding
    # - bitsandbytes
    # - bitsandbytes-cuda117    # from https://pypi.org/project/bitsandbytes-cuda113/
    - faiss-cpu
    - lancedb
    - tifffile
